name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    env:
      NEXT_PUBLIC_COINGECKO_BASE_URL: ${{ secrets.NEXT_PUBLIC_COINGECKO_BASE_URL }}
      NEXT_PUBLIC_COIN_API_KEY: ${{ secrets.NEXT_PUBLIC_COINGECKO_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
