name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    env:
      COINGECKO_BASE_URL: ${{ secrets.COINGECKO_BASE_URL }}
      COIN_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
